/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unigrupo94.Vistas;

import java.time.ZoneId;
import java.util.Date;
import unigrupo94.AccesoADatos.AlumnoData;
import unigrupo94.Entidades.Alumno;

/**
 *
 * @author JATil
 */
public class GestionDeAlumnos extends javax.swing.JInternalFrame {
    private int idAlumno; 
    /**
     * Creates new form GestionDeAlumnos
     */
    public GestionDeAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTDni = new javax.swing.JTextField();
        jTBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTEliminar = new javax.swing.JButton();
        jTGuardar = new javax.swing.JButton();
        jtEstado = new javax.swing.JRadioButton();
        jTFNacimiento = new com.toedter.calendar.JDateChooser();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("ALUMNOS");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("DNI");

        jTBuscar.setText("Buscar");
        jTBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("APELLIDO");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("NOMBRE");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("ESTADO");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("F. NA:");

        jTEliminar.setText("Eliminar");
        jTEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEliminarActionPerformed(evt);
            }
        });

        jTGuardar.setText("Guardar");
        jTGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTGuardar)
                        .addGap(53, 53, 53))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtEstado)
                            .addComponent(jTFNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTBuscar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1)))
                .addGap(0, 69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jtEstado))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jTFNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jTBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTEliminar)
                    .addComponent(jTGuardar))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBuscarActionPerformed
        //BUSCAR ALUMNO
        int num = Integer.parseInt(jTDni.getText());
        System.out.println(num);
        
        AlumnoData ad = new AlumnoData ();
        Alumno alumno = ad.buscarAlumnoPorDni(num);
        System.out.println(alumno.getNombre()+ " " + alumno.getApellido());
        
        jTApellido.setText(alumno.getApellido());
        jTNombre.setText(alumno.getNombre());
        jtEstado.setSelected(alumno.isActivo());
        ZoneId zoneId = ZoneId.systemDefault();
        //A LA FECHA DE NACIMIENTO UTILIZAMOS EL METODO "atStartOfDay" QUE SIRVE PARA COMBIAR FECHA CON LA HORA DE LA MEDIANOCHE 
        // PARA CREAR UN LocalDateTime AL COMIENZO DE LA FECHA CON MI INSTANT OBTUVE EL INSTANTE DE LA FECHA, UNA VEZ OBTENIDA EL INSTANTE
        //ULTILIZO EL METODO ESTATICO FROM DE LA CLASE DATE(java.util.Date)
        jTFNacimiento.setDate(Date.from(alumno.getFechaNac().atStartOfDay(zoneId).toInstant()));
        idAlumno = alumno.getIdAlumno();
    }//GEN-LAST:event_jTBuscarActionPerformed

    private void jTGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTGuardarActionPerformed
        // GUARDAR ALUMNO 
        AlumnoData ad = new AlumnoData(); 
        Alumno alumno = new Alumno (); 
        alumno.setDni(Integer.parseInt(jTDni.getText()));
        alumno.setApellido(jTApellido.getText());
        alumno.setNombre(jTNombre.getText());
        alumno.setActivo(jtEstado.isSelected());
        alumno.setFechaNac(jTFNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        ad.guardarAlumno(alumno);
        
    }//GEN-LAST:event_jTGuardarActionPerformed

    private void jTEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEliminarActionPerformed
        // ELIMINAR ALUMNO
        System.out.println("ID DE ALUMNO A ELIMINAR: " + idAlumno);
        AlumnoData ad = new AlumnoData ();
        ad.eliminarAlumno(idAlumno);
        idAlumno = 0 ; 
        jTApellido.setText("");
        jTNombre.setText("");
        jtEstado.setSelected(false);
        jTFNacimiento.setToolTipText("");
    }//GEN-LAST:event_jTEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JButton jTBuscar;
    private javax.swing.JTextField jTDni;
    private javax.swing.JButton jTEliminar;
    private com.toedter.calendar.JDateChooser jTFNacimiento;
    private javax.swing.JButton jTGuardar;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JRadioButton jtEstado;
    // End of variables declaration//GEN-END:variables
}
